(defun grand-total (a-number)
    (cond ((not (integerp a-number)) nil)
        ((<= a-number 0) nil)
        ((= a-number 1) 1)
        (t (+ a-number (grand-total (- a-number 1))))
    )
)

(defun grand-totals (a-number)
    (cond ((not (integerp a-number)) nil)
        ((<= a-number 0))
        (t (progn
            (princ "1から")
            (princ a-number) 
            (princ "までの総和は")
            (princ (grand-total a-number))
            (princ "です.")
            (princ #\newline)
            (grand-totals (- a-number 1))
            )
        )
    )
)

(grand-totals (read))
