(defun operators (first-number second-number)
    (progn
        (princ first-number)
        (princ "+")
        (princ second-number)
        (princ "=")
        (princ (+ first-number second-number))
        (princ #\newline)
    )
    (progn
        (princ first-number)
        (princ "-")
        (princ second-number)
        (princ "=")
        (princ (- first-number second-number))
        (princ #\newline)
    )
    (progn
        (princ first-number)
        (princ "*")
        (princ second-number)
        (princ "=")
        (princ (* first-number second-number))
        (princ #\newline)
    )
    (progn
        (princ first-number)
        (princ "/")
        (princ second-number)
        (princ "=")
        (princ (/ first-number second-number))
        (princ #\newline)
    )
    (progn
        (princ first-number)
        (princ "%")
        (princ second-number)
        (princ "=")
        (princ (rem first-number second-number))
        (princ #\newline)
    )
)

(operators (read) (read))